In [14]:
import pandas as pd
from sklearn import *
import numpy as np
from sklearn.tree import *
import matplotlib.pyplot as plt
import json
import seaborn as sns

df = pd.read_csv("../data-master/credit-default.csv")
df.head(5)

,checking_balance,months_loan_duration,credit_history,purpose,amount,savings_balance,employment_length,installment_rate,personal_status,other_debtors,...,property,age,installment_plan,housing,existing_credits,default,dependents,telephone,foreign_worker,job
0,< 0 DM,6,critical,radio/tv,1169,unknown,> 7 yrs,4,single male,none,...,real estate,67,none,own,2,1,1,yes,yes,skilled employee
1,1 - 200 DM,48,repaid,radio/tv,5951,< 100 DM,1 - 4 yrs,2,female,none,...,real estate,22,none,own,1,2,1,none,yes,skilled employee
2,unknown,12,critical,education,2096,< 100 DM,4 - 7 yrs,2,single male,none,...,real estate,49,none,own,1,1,2,none,yes,unskilled resident
3,< 0 DM,42,repaid,furniture,7882,< 100 DM,4 - 7 yrs,2,single male,guarantor,...,building society savings,45,none,for free,1,1,2,none,yes,skilled employee
4,< 0 DM,24,delayed,car (new),4870,< 100 DM,1 - 4 yrs,3,single male,none,...,unknown/none,53,none,for free,2,2,2,none,yes,skilled employee

In [9]:
df.default.value_counts()

1    700
2    300
Name: default, dtype: int64

In [15]:
# dependent variable/target varible/label
label = "default"

# independepent variables/features/predictors
X = df.drop(columns=[label])


# vector for target variable
y = np.log(df[label])

# one hot encoding to conver categorical features into numeric
# drop_first: remove first value of a categorical feature ... it is redundant
X = pd.get_dummies(X, drop_first=True)

# Creating trainnig and test sets
# test_size is 30% of the whole
# random_state: to reprduce the same combination of training and test records
X_train, X_test, y_train, y_test = model_selection.train_test_split(X.values,                       
                                    y, test_size = 0.3, random_state = 1)


pipe = pipeline.Pipeline([
    ("poly", preprocessing.PolynomialFeatures(degree=1, include_bias=False)),
    ("scaler", preprocessing.StandardScaler()),
    ("pca", decomposition.PCA(n_components=0.9)),
    ("est", linear_model.LinearRegression())
])

pipe.fit(X_train, y_train)

# prediction on training and test data
y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)

print("R2 training:", metrics.r2_score(y_train, y_train_pred))
print("R2 test:", metrics.r2_score(y_test, y_test_pred))

print("Rmse training:", np.sqrt(metrics.mean_squared_error(y_train, y_train_pred)))
print("Rmse: testing", np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))

R2 training: 0.2669711671853341
R2 test: 0.1940187721653962
Rmse training: 0.2734091036254444
Rmse: testing 0.28139915047280467

In [16]:
metrics.confusion_matrix(y_test,+)

ValueError: continuous is not supported

SyntaxError: invalid syntax (<ipython-input-5-bef1e2b494a1>, line 10)